Fix sql equality "=" instead of "==" in postgres
```
Traceback (most recent call last):
  File "/virtualenv/env3/lib/python3.7/site-packages/xdoctest/doctest_example.py", line 598, in run
    exec(code, test_globals)
  File "<doctest:/wbia/wildbook-ia/wbia/algo/hots/neighbor_index_cache.py::build_nnindex_cfgstr:0>", line rel: 5, abs: 214, in <module>
    >>> daid_list = ibs.get_valid_aids(species=wbia.const.TEST_SPECIES.ZEB_PLAIN)
  File "/wbia/wildbook-ia/wbia/control/manual_annot_funcs.py", line 806, in get_valid_aids
    min_timedelta=min_timedelta,
  File "/wbia/wildbook-ia/wbia/control/manual_annot_funcs.py", line 877, in filter_annotation_set
    aid_list = ibs.filter_aids_to_species(aid_list, species)
  File "/wbia/wildbook-ia/wbia/other/ibsfuncs.py", line 5104, in filter_aids_to_species
    aid_list_ = ut.take_column(ibs.db.connection.execute(operation).fetchall(), 0)
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1178, in _execute_text
    parameters,
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) operator does not exist: integer == integer
LINE 1: ...ELECT rowid from annotations WHERE (species_rowid == 1) AND ...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

[SQL: SELECT rowid from annotations WHERE (species_rowid == 1) AND rowid IN (1,2,3,4,5,6,7,8,9,10,11,12,13)]
(Background on this error at: http://sqlalche.me/e/13/f405)
DOCTEST REPRODUCTION
CommandLine:
    pytest /wbia/wildbook-ia/wbia/algo/hots/neighbor_index_cache.py::build_nnindex_cfgstr:0
/wbia/wildbook-ia/wbia/algo/hots/neighbor_index_cache.py:214: ProgrammingError
```