Fix rowid integer casting code in SQLDatabaseController
```
id_iter = [id_ is not None and int(id_) or id_ for id_ in id_iter]
```

if `id_` is `np.int64(0)`, `int(id_)` returns 0 and `int(id_) or id_`
returns `id_` so it is not casted to an integer correctly.

```
Traceback (most recent call last):
  File "/virtualenv/env3/lib/python3.7/site-packages/xdoctest/doctest_example.py", line 598, in run
    exec(code, test_globals)
  File "<doctest:/wbia/wildbook-ia/wbia/annotmatch_funcs.py::set_annot_pair_as_negative_match:0>", line rel: 7, abs: 626, in <module>
    >>> result = set_annot_pair_as_negative_match(ibs, aid1, aid2, dryrun)
  File "/wbia/wildbook-ia/wbia/annotmatch_funcs.py", line 696, in set_annot_pair_as_negative_match
    next_nids = ibs.make_next_nids(num=1)
  File "/wbia/wildbook-ia/wbia/other/ibsfuncs.py", line 3020, in make_next_nids
    location_text=location_text,
  File "/wbia/wildbook-ia/wbia/other/ibsfuncs.py", line 3104, in make_next_name
    species_code = ibs.get_species_codes(species_rowid)
  File "/wbia/wbia-utool/utool/util_decor.py", line 452, in wrp_asi
    ret = func(self, [input_], *args, **kwargs)
  File "/wbia/wildbook-ia/wbia/control/accessor_decors.py", line 470, in wrp_getter
    return func(*args, **kwargs)
  File "/wbia/wildbook-ia/wbia/control/manual_species_funcs.py", line 556, in get_species_codes
    const.SPECIES_TABLE, (SPECIES_CODE,), species_rowid_list
  File "/wbia/wildbook-ia/wbia/dtool/sql_control.py", line 1382, in get
    tblname, colnames, params_iter, where_clause, eager=eager, **kwargs
  File "/wbia/wildbook-ia/wbia/dtool/sql_control.py", line 1228, in get_where
    **kwargs,
  File "/wbia/wildbook-ia/wbia/dtool/sql_control.py", line 1671, in executemany
    value = self.executeone(operation, params, keepwrap=keepwrap)
  File "/wbia/wildbook-ia/wbia/dtool/sql_control.py", line 1621, in executeone
    results = self.connection.execute(operation, params)
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)

sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'numpy.int64'
[SQL: SELECT _ibeis_database.species.species_code
FROM _ibeis_database.species
WHERE rowid = %(_identifier)s]
[parameters: {'_identifier': 0}]
(Background on this error at: http://sqlalche.me/e/13/f405)
DOCTEST REPRODUCTION
CommandLine:
    pytest /wbia/wildbook-ia/wbia/annotmatch_funcs.py::set_annot_pair_as_negative_match:0
```